{
    "prompt": "A dog sitting on grass",
    "negative_prompt": "low quality",
    "edit_prompt": "A golden retriever sitting on grass",
    "src_img_path": "./sds_outputs/A_dog_sitting_on_grass.png",
    "save_dir": "pds_outputs/A_dog_sitting_on_grass",
    "loss_type": "pds",
    "guidance_scale": 25.0,
    "step": 500,
    "device": 0,
    "lr": 0.001,
    "log_step": 25,
    "precision": "fp32"
}