{
    "prompt": "A villa close to the pool",
    "negative_prompt": "low quality",
    "edit_prompt": "A villa covered with ivy close to the pool",
    "src_img_path": "./sds_outputs/A_villa_close_to_the_pool.png",
    "save_dir": "pds_outputs/A_villa_close_to_the_pool",
    "loss_type": "pds",
    "guidance_scale": 25.0,
    "step": 500,
    "device": 0,
    "lr": 0.001,
    "log_step": 25,
    "precision": "fp32"
}