{
    "prompt": "A castle next to a river",
    "negative_prompt": "low quality",
    "edit_prompt": "A rainbow castle next to a river",
    "src_img_path": "./sds_outputs/A_castle_next_to_a_river.png",
    "save_dir": "pds_outputs/A_castle_next_to_a_river",
    "loss_type": "pds",
    "guidance_scale": 25.0,
    "step": 500,
    "device": 0,
    "lr": 0.001,
    "log_step": 25,
    "precision": "fp32"
}