{
    "prompt": "A cabin surrounded by forests",
    "negative_prompt": "low quality",
    "edit_prompt": "A cabin surrounded by flowers",
    "src_img_path": "./sds_outputs/A_cabin_surrounded_by_forests.png",
    "save_dir": "pds_outputs/A_cabin_surrounded_by_forests",
    "loss_type": "pds",
    "guidance_scale": 25.0,
    "step": 500,
    "device": 0,
    "lr": 0.001,
    "log_step": 25,
    "precision": "fp32"
}