{
    "prompt": "A red bus driving on a desert road",
    "negative_prompt": "low quality",
    "edit_prompt": null,
    "src_img_path": null,
    "save_dir": "outputs/A_red_bus_driving_on_a_desert_road",
    "loss_type": "sds",
    "guidance_scale": 25.0,
    "step": 500,
    "device": 0,
    "lr": 0.001,
    "log_step": 25,
    "precision": "fp32"
}